### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by EdenMelaku** [endalk200/CodeTopia#7]
i know it is early to ask this question, but does it Run? cus i got some attribute errors. 

and another question what Django version are you using ? i think we need to be on the same version to avoid some errors.

**Comment by endalk200** [comment]
After you clone the repository you should run the following commands in your terminal.
```bash
pipenv install
```
then activate your environment by runing
```bash
pipenv shell
```
then your good to go just run
```bash
python manage.py runserver
```
